### ISSUE TITLE
'unarchiveTopLevelObjectWithData' is unavailable

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [artemstepanenko/Dekoter#20]
Hi,

I installed the library on a Xcode 9 (beta 4) project via CocoaPods.

```
platform :ios, '9.0'

target 'DekoterDemo' do
  use_frameworks!

  pod 'Dekoter'

end
```

It installed the v0.3.0 of Dekoter. Then I built the project and I get the following compile error in the `NSKeyedUnarchiver+Dekoter.swift` file inside the `de_unarchiveObject` method.

> 'unarchiveTopLevelObjectWithData' is unavailable

**Comment by artemstepanenko** [comment]
Hello, @Isuru-Nanayakkara . Thanks for this issue!
Looks like the problem is that the `unarchiveTopLevelObjectWithData` method has a different name in **swift 4** (which is introduced in your brand new **Xcode 9**). I plan to convert the pod to **swift 4** a little later when a final version of **Xcode 9** is released. As a temporary solution please check this [question/answer](https://stackoverflow.com/a/45312048/1090309).

P.S. Please let me know whether it helps.

**Comment by Isuru-Nanayakkara** [comment]
Thanks, @artemstepanenko for the prompt reply!
